contact_links:
  - name: Contributing Guide
    url: https://github.com/TheOtterlord/SemanticBumper/blob/master/CONTRIBUTING.md
    about: Not sure where to start? Check out our contributing guidelines